---
name: Net-Social-Service-Jabber
version: 0.1
author:
  - 'Simon Wistow <simon@thegestalt.org>'
abstract: a Jabber plugin for Net::Social
license: unknown
requires:
  Jabber::Connection: 0
  Net::Social: 0
  Test::More: 0.62
provides:
  Net::Social::Service::Jabber:
    file: lib/Net/Social/Service/Jabber.pm
    version: 0.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
